### ISSUE TITLE
set rules for the development workflow

### ISSUE THREAD

**Issue by razr** [ros-realtime/rtwg_documentation#10]
We have agreed to set rules like:
- the submitter of the pull request shall set up at least one reviewer
- after the review is completed whether the reviewer or another person who has write access should merge changes

**Comment by LanderU** [comment]
@razr @carlossvg, the following rules are configured:

* 2 code owners approves are needed to merge the PR
* Default branch is rolling and is protected
* CI should pass
* Foxy is also protected with the same rules
