### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by razr** [ros-realtime/rtwg_documentation#19]

**Comment by razr** [comment]
Do we want to add the same license as https://github.com/ros2/ros2_documentation/blob/rolling/LICENSE

**Comment by LanderU** [comment]
@razr, I'm not a big License expert, so, creative commons license sounds good to me. @carlossvg?

**Comment by carlossvg** [comment]
@razr @LanderU I agree, I would simply use the same ones as the ros 2 docs
