### ISSUE TITLE
De-duplicate RT kernel build instructions

### ISSUE THREAD

**Issue by christophebedard** [ros-realtime/rtwg_documentation#29]
There's a guide for building a RT kernel here: https://real-time-working-group.readthedocs.io/en/latest/Guides/Real-Time-Operating-System-Setup/Real-Time-Linux/build_rt_kernel.html

but the instructions here are slightly more up-to-date/better: https://github.com/ros-realtime/rt-kernel-docker-builder

Should the guide be updated with the text from the README? And to de-duplicate we can remove it from the README and point to the guide in the documentation.

**Comment by razr** [comment]
@christophebedard indeed, docs part shall be updated. Thanks for pointing it out. 
Let me do it. I'm not sure what is the right split between the guide and the README. I think the guide shall be not so detailed as a README. Probably it should more describe a "why" to configure and "what" to configure and a README the "how"?

**Comment by christophebedard** [comment]
> I'm not sure what is the right split between the guide and the README. I think the guide shall be not so detailed as a README. Probably it should more describe a "why" to configure and "what" to configure and a README the "how"?

I was thinking about just removing all the content from one of them and replacing it with a link to the other (i.e. update the guide with the content of the README, empty out the README, and replace with link to the guide). As you wish though, if you think the split should be somewhere in the middle I think that's fine. I'm mostly just bringing this up to remove the duplication.

**Comment by carlossvg** [comment]
@christophebedard I agree, I think it's better to have a single source of truth. I would remove the readme from the tool repository and replace it with a link to the documentation. 

I think we should do the same with the community repo readme. I will go trough the readmes and clean-up the documentation.

**Comment by carlossvg** [comment]
Moved to https://github.com/ros-realtime/ros-realtime.github.io/issues/9
