### ISSUE TITLE
Raspberry PI Real time kernel

### ISSUE THREAD

**Issue by chandravaran** [ros-realtime/rtwg_documentation#35]
I see that there is nothing updated for raspberry pi real time kernel, so I was wondering when will it be updated, or if possible you you suggest some links to keep a real time kernel

**Comment by carlossvg** [comment]
Hi @chandravaran 

You can build a real-time kernel for the Raspberry-PI using this guide here: https://real-time-working-group.readthedocs.io/en/latest/Guides/Real-Time-Operating-System-Setup/Real-Time-Linux/build_rt_kernel_using_docker.html

We wanted to create a ready-to-use real-time RPI image but it's too large to host it in Github. We will probably upload the `.debs`  mentioned in the guide so you can simply download and install them using `dpkg`.

Your feedback is very useful, if you think having an RPI image would be helpful we can find a way to host them.

cc @LanderU @razr

**Comment by carlossvg** [comment]
This is done now as part of https://github.com/ros-realtime/ros-realtime-rpi4-image. We will update the documentation once we create a release.
