### ISSUE TITLE
Update hosting and copyright

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/rtwg_documentation#4]
Acceptance criteria
- [ ] The docs are hosted using a shared account owned by the RTWG
- [x] Copyright is updated

**Comment by LanderU** [comment]
@carlossvg, regarding copyright, shall I remove it completely or do you want me to set something there?

**Comment by LanderU** [comment]
Ejem: `© Copyright 2021, Real-time working group.`?

**Comment by carlossvg** [comment]
@LanderU TODO: document how the RTWG documentation is hosted and how to transfer it to other owner
